# Generated by Django 2.2.5 on 2019-11-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateField(blank=True),
        ),
    ]
